config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:index, :show, :edit, :update] do
      resources :relationships, except: %i[index new create edit update show destroy] do
        member do
          post :follow
          delete :unfollow
        end
      end
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "library" => "relationships#library", as: "library"
      patch 'users/withdraw', as: 'withdraw'
      resources :calendars, only: [:index, :create, :destroy]
    end

    resources :articles, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :article_comments, only: [:create, :edit, :update, :destroy]
      resource :favorites, only: [:create, :destroy]

    end
    get 'index' => 'favorites#index', as: 'favorite_index'
    get 'search' => 'searches#search'
    get "genre_search" => "searches#genre_search"
    get "users_search" => "searches#users_search"
  end

  namespace :admin do
    resources :body_part_genres, only: [:index, :create, :edit, :update]

    resources :gear_genres, only: [:index, :create, :edit, :update]

    resources :articles,  only: [:index, :show, :destroy] do
      resources :article_comments, only: [:destroy]
    end
    resources :users, only: [:index, :show] do
      patch 'users/withdraw', as: 'withdraw'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gear_genre.rb
class GearGenre < ApplicationRecord
  has_many :articles, dependent: :destroy

  has_one_attached :gear_genre_icon

  validates :name, presence: true
  validates :gear_genre_icon, presence: true


end

app/controllers/admin/gear_genres_controller.rb
class Admin::GearGenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @gear_genres = GearGenre.all
    @gear_genre = GearGenre.new
  end

  def edit
    @gear_genre = GearGenre.find(params[:id])
  end

  def update
    @gear_genre = GearGenre.find(params[:id])
    if @gear_genre.update(gear_genre_params)
      @gear_genres = GearGenre.all
      redirect_to admin_body_part_genres_path
      flash[:notice] = "ジャンルを更新しました"
    else
      render :edit
    end
  end

  def new
  end

  def create
    @gear_genres = GearGenre.all
    @gear_genre = GearGenre.new(gear_genre_params)
    if @gear_genre.save
      flash[:notice] = "ジャンルを作成しました"
    end
  end

  private
  def gear_genre_params
    params.require(:gear_genre).permit(:name, :gear_genre_icon)
  end
end

app/controllers/gear_genres_controller.rb
class GearGenresController < ApplicationController
  def index
  end

  def edit
  end

  def new
  end

  def create
  end

  private
  def gear_genre_params
    params.reruire(:gear_genre).permit(:name)
  end
end

app/helpers/gear_genres_helper.rb
module GearGenresHelper
end

app/views/admin/gear_genres/_index.html.erb
<% @gear_genres.each do |gear_genre| %>
  <tr>
    <td>
      <%= image_tag gear_genre.gear_genre_icon, size: "20x20" %>
        <%= gear_genre.name %>
    </td>
    <td><%= link_to "ジャンル編集",edit_admin_gear_genre_path(gear_genre) %></td>
  </tr>
<% end %>

app/views/admin/gear_genres/create.js.erb
$('#gear_genres').html("<%= j(render "admin/gear_genres/index", gear_genres: @gear_genres) %>");
$('#flash-message').html('<%= j(render "layouts/flash_message") %>');
$('#erorr').html("<%= j(render 'layouts/error_messages', model: @gear_genre) %>");
$(".text_field").val("");
$(".file_field").val("");

function sleep(msec) {
   return new Promise(function(resolve) {

      setTimeout(function() {resolve()}, msec);

   })
};

$(document).ready(function (){
  $('#flash-message').slideDown(1000,async function start(){
    await sleep(2000);
    $('#flash-message').slideUp(1000);
  });
});

app/views/admin/gear_genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 ml-5 mb-3">
      <h2>ジャンル編集</h2>
    </div>
    <div id="erorr">
      <%= render "layouts/error_messages", model: @gear_genre %>
    </div>
    <div class="col-lg-8 mx-auto">
      <%= form_with model: @gear_genre,url: admin_gear_genre_path do |f| %>
        <div class="form-group">
         <%= f.label :トレーニング部位 %>
         <%= f.text_field :name  %>
       </div>
       <div class="form-group">
         <%= f.label :ジャンルアイコン %>
         <%= f.file_field :gear_genre_icon  %>
       </div>
       <div class="text-center mr-5 pr-5"><%= f.submit "ジャンル更新", class:"btn light_green btn-sm" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/gear_genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <%= form_with model: @gear_genre, url: admin_gear_genres_path, method: :post do |f| %>
       <%= f.label :使用器具 %>
       <%= f.text_field :name  %>
       <%= f.label :ジャンルアイコン %>
       <%= f.file_field :gear_genre_icon  %>
       <%= f.submit "新規投稿" %>
      <% end %>

      <div class="row my-4">
        <table class="table">
          <thead>
            <tr>
              <td>テーブル名</td>
              <td></td>
            </tr>
          </thead>
          <tbody>
            <% @gear_genres.each do |gear_genre| %>
              <tr>
                <td>
                  <%= image_tag gear_genre.gear_genre_icon, size: "20x20" %>
                  　　<%= gear_genre.name %>
                  </td>
                <td><%= link_to "ジャンル名編集",edit_admin_gear_genre_path(gear_genre) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>