config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:index, :show, :edit, :update] do
      resources :relationships, except: %i[index new create edit update show destroy] do
        member do
          post :follow
          delete :unfollow
        end
      end
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "library" => "relationships#library", as: "library"
      patch 'users/withdraw', as: 'withdraw'
      resources :calendars, only: [:index, :create, :destroy]
    end

    resources :articles, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :article_comments, only: [:create, :edit, :update, :destroy]
      resource :favorites, only: [:create, :destroy]

    end
    get 'index' => 'favorites#index', as: 'favorite_index'
    get 'search' => 'searches#search'
    get "genre_search" => "searches#genre_search"
    get "users_search" => "searches#users_search"
  end

  namespace :admin do
    resources :body_part_genres, only: [:index, :create, :edit, :update]

    resources :gear_genres, only: [:index, :create, :edit, :update]

    resources :articles,  only: [:index, :show, :destroy] do
      resources :article_comments, only: [:destroy]
    end
    resources :users, only: [:index, :show] do
      patch 'users/withdraw', as: 'withdraw'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/body_part_genre.rb
class BodyPartGenre < ApplicationRecord
  has_many :articles, dependent: :destroy

  has_one_attached :body_part_icon

  validates :name, presence: true
  validates :body_part_icon, presence: true
end

app/controllers/admin/body_part_genres_controller.rb
class Admin::BodyPartGenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @body_part_genres = BodyPartGenre.all
    @body_part_genre = BodyPartGenre.new
    @gear_genres = GearGenre.all
    @gear_genre = GearGenre.new
  end

  def edit
    @body_part_genre = BodyPartGenre.find(params[:id])
  end

  def update
    @body_part_genre = BodyPartGenre.find(params[:id])
    if @body_part_genre.update(body_part_genre_params)
      @body_part_genres = BodyPartGenre.all
      redirect_to admin_body_part_genres_path
      flash[:notice] = "ジャンルを更新しました"
    else
      render :edit
    end
  end

  def create
    @body_part_genre = BodyPartGenre.new(body_part_genre_params)
    @body_part_genres = BodyPartGenre.all
    if @body_part_genre.save
      flash[:notice] = "ジャンルを作成しました"
    end
  end

  private
  def body_part_genre_params
    params.require(:body_part_genre).permit(:name, :body_part_icon)
  end
end

app/helpers/body_part_genre_helper.rb
module BodyPartGenreHelper
end

app/views/admin/body_part_genres/_index.html.erb
<% body_part_genres.each do |body_part_genre| %>
  <tr>
    <td>
      <%= image_tag body_part_genre.body_part_icon, size: "20x20" %>
      　　<%= body_part_genre.name %>
    </td>
    <td><%= link_to "ジャンル編集",edit_admin_body_part_genre_path(body_part_genre) %></td>
  </tr>
<% end %>

app/views/admin/body_part_genres/create.js.erb
$('#body_part_genres').html("<%= j(render "admin/body_part_genres/index", body_part_genres: @body_part_genres) %>");
$('#flash-message').html('<%= j(render "layouts/flash_message") %>');
$(".text_field").val("");
$(".file_field").val("");
$('#erorr').html("<%= j(render 'layouts/error_messages', model: @body_part_genre) %>");

function sleep(msec) {
   return new Promise(function(resolve) {

      setTimeout(function() {resolve()}, msec);

   })
};

$(document).ready(function (){
  $('#flash-message').slideDown(1000,async function start(){
    await sleep(2000);
    $('#flash-message').slideUp(1000);
  });
});

app/views/admin/body_part_genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 ml-5 mb-3">
      <h2>ジャンル編集</h2>
    </div>
    <div id="erorr">
      <%= render "layouts/error_messages", model: @body_part_genre %>
    </div>
    <div class="col-lg-8 mx-auto">
      <%= form_with model: @body_part_genre,url: admin_body_part_genre_path, method: :patch do |f| %>
        <div class="form-group">
         <%= f.label :トレーニング部位 %>
         <%= f.text_field :name  %>
       </div>
       <div class="form-group">
         <%= f.label :ジャンルアイコン %>
         <%= f.file_field :body_part_icon  %>
       </div>
       <div class="text-center mr-5 pr-5"><%= f.submit "ジャンル更新", class:"btn light_green btn-sm" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/body_part_genres/index.html.erb
<div class="container">
  <div id="erorr">
    <%= render "layouts/error_messages", model: @body_part_genre %>
  </div>
  <div id="erorr">
    <%= render "layouts/error_messages", model: @gear_genre %>
  </div>
  <div class="col-lg-4 ml-5 mb-3">
    <h2>ジャンル一覧</h2>
  </div>
  <div class="row">
    <div class="col-lg-6 mt-4">
      <%= form_with model: @body_part_genre, url: admin_body_part_genres_path, method: :post, local: false do |f| %>
       <div class="form-group">
         <%= f.label :トレーニング部位 %>
         <%= f.text_field :name , class:"text_field" %>
       </div>
       <div class="form-group">
         <%= f.label :ジャンルアイコン %>
         <%= f.file_field :body_part_icon, class:"file_field"  %>
       </div>
       <div class="text-center mr-5 pr-5"><%= f.submit "ジャンル作成", class:"btn light_green btn-sm" %></div>
      <% end %>

      <div class="row my-4">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>トレーニング部位</td>
              <td></td>
            </tr>
          </thead>
          <tbody  id="body_part_genres">
            <%= render "admin/body_part_genres/index", body_part_genres: @body_part_genres %>
          </tbody>
        </table>
      </div>
    </div>
        <div class="col-lg-6 mt-4">
      <%= form_with model: @gear_genre, url: admin_gear_genres_path, method: :post, local: false do |f| %>
        <div class="form-group">
          <i class="mr-5"><%= f.label :使用器具名 %></i>
          <%= f.text_field :name, class:"text_field"  %>
        </div>
        <div class="form-group">
          <%= f.label :ジャンルアイコン %>
          <%= f.file_field :gear_genre_icon, class:"file_field"  %>
        </div>
        <div class="text-center mr-5 pr-5 "><%= f.submit "ジャンル作成", class:"btn light_green btn-sm"%></div>
      <% end %>

      <div class="row my-4">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>使用器具</td>
              <td></td>
            </tr>

          </thead>
          <tbody id="gear_genres">
           <%= render "admin/gear_genres/index", gear_genres: @gear_genres %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>