config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:index, :show, :edit, :update] do
      resources :relationships, except: %i[index new create edit update show destroy] do
        member do
          post :follow
          delete :unfollow
        end
      end
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "library" => "relationships#library", as: "library"
      patch 'users/withdraw', as: 'withdraw'
      resources :calendars, only: [:index, :create, :destroy]
    end

    resources :articles, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :article_comments, only: [:create, :edit, :update, :destroy]
      resource :favorites, only: [:create, :destroy]

    end
    get 'index' => 'favorites#index', as: 'favorite_index'
    get 'search' => 'searches#search'
    get "genre_search" => "searches#genre_search"
    get "users_search" => "searches#users_search"
  end

  namespace :admin do
    resources :body_part_genres, only: [:index, :create, :edit, :update]

    resources :gear_genres, only: [:index, :create, :edit, :update]

    resources :articles,  only: [:index, :show, :destroy] do
      resources :article_comments, only: [:destroy]
    end
    resources :users, only: [:index, :show] do
      patch 'users/withdraw', as: 'withdraw'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :body_part_genre
  belongs_to :gear_genre
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :calendars, dependent: :destroy

  has_one_attached :article_image
  has_one_attached :article_image2
  has_one_attached :article_image3
  has_one_attached :article_image4

  validates :title, presence: true
  validates :text, length: {maximum: 500}
  validates :body_part_genre, presence: true
  validates :gear_genre, presence: true
  validates :method1_text, presence: true

  def get_article_image(width, height)
    unless article_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      article_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    article_image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def Article.looks(search, word)
    if search == "完全一致"
      @article = Article.where("title LIKE?", "#{word}")
    elsif search == "曖昧検索"
      @article = Article.where("title LIKE?", "%#{word}%")
    else
      @article = Article.all
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @article_comments = ArticleComment.where(article_id: @article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
    flash.now[:notice] = "投稿を削除しました"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
  
  def create
  end
  
  def destroy
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :text, :article_image, :body_part_genre_id, :gear_genre_id, :article_genre ,:user_id)
  end 
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article_index.html.erb
<div class="row border p-2">
  <div class="w-25 h-100" style="text-align : center">
    <%= link_to admin_article_path(article)  do %>
      <%= image_tag article.get_article_image(200,150) %>
    <% end %>
    <div class="mt-1"><%= link_to article.user.name, admin_user_path(article.user) %></div>
  </div>
  <div class="d-flex flex-column bd-highlight mb-3">
    <div class="p-2 bd-highlight">
      <h5 class="pl-4"><%= article.title %></h5>
    </div>
    <div class="p-2 bd-highlight ml-5 mr-4">
      <%= article.text %>
    </div>
    <div class="mt-5 bd-highlight">
    <i class=" ml-5"><%= image_tag article.gear_genre.gear_genre_icon, size: "20x20" %></i>
    <i class="ml-5"> <%= image_tag article.body_part_genre.body_part_icon, size: "20x20" %></i>
    <i class="ml-5">
      <%= article.favorites.count %>:♥
    </i>
    <i class="ml-5">
      <%= link_to admin_article_path(article) do %>
        <%= article.article_comments.count %>💬
      <% end %>
    </i>
    </div>
  </div>

</div>

app/views/admin/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 ml-5 mb-3">
      <h2>投稿一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>投稿ユーザー名</th>
            <th>投稿タイトル</th>
            <th>投稿日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td><%= link_to article.user.name, admin_user_path(article.user) %></td>
              <td><%= link_to article.title, admin_article_path(article) %></td>
              <td><%= article.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= link_to "投稿を削除する", admin_article_path(article), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger btn-sm"%></td>
            </tr>
          <% end %>
        </tbody>
      </tabla>
    </div>
  </div>
</div>

app/views/admin/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">
        <%= render "admin/articles/article_index", article: @article %>
          <div class="row mt-3">
            <div class="col-lg-8"><h3>トレーニング手順</h3></div>
            <div class="col-lg-4">
              <i class="ml-3"><%= link_to "投稿を削除する", article_path(@article), method: :delete, class: "btn btn-outline-danger", data: {confirm:"本当に削除しますか？"} %></i>
            </div>
          </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="mt-4 mb-3"><%= image_tag @article.article_image.variant(resize_to_fill: [150, 150]) %></div>
          </div>
          <div class="col-lg-8">
            <div class="mt-4 mb-3 p-3"><%= @article.method1_text %></div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <% if @article.article_image2.attached? %>
              <div class="mt-4 mb-3"><%= image_tag @article.article_image2.variant(resize_to_fill: [150, 150]) %></div>
            <% end %>
          </div>
          <div class="col-lg-8">
            <div class="mt-4 mb-3 p-3"><%= @article.method2_text %></div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <% if @article.article_image3.attached? %>
              <div class="mt-4 mb-3"><%= image_tag @article.article_image3.variant(resize_to_fill: [150, 150]) %></div>
            <% end %>
          </div>
          <div class="col-lg-8">
            <div class="mt-4 mb-3 p-3"><%= @article.method3_text %></div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <% if @article.article_image4.attached? %>
              <div class="mt-4 mb-3"><%= image_tag @article.article_image4.variant(resize_to_fill: [150, 150]) %></div>
            <% end %>
          </div>
          <div class="col-lg-8">
            <div class="mt-4 mb-3 p-3"><%= @article.method4_text %></div>
          </div>
        </div>

        <div class="row">
          <h3 class="ml-3">コメント一覧</h3>
          <table class="table table-hover">
            <thead>
              <td>投稿者</td>
              <td>コメント</td>
              <td></td>
              <td></td>
            </thead>
            <tbody id="comments">
               <%= render "admin/article_comments/comment_index", article_comments: @article_comments, article: @article %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>